---
title: "Exploring Consumer Complaints"
author: "Darshan Sumant"
date: "February 3, 2019"
output: 
  html_document:
    toc: TRUE
    toc_float: TRUE
    code_folding: hide
---

```{r setup, include=FALSE}

# Load required packages
library("rmarkdown")
library("readr")
library("haven")
library("plyr")
library("dplyr")
library("tidyr")
library("stringr")
library("ggplot2")
library("zoo")
library("lubridate")
library("directlabels")
library("wesanderson")
library("maps")
library("mapdata")
library("openintro")
library("grid")

knitr::opts_chunk$set(echo = TRUE, warning = FALSE)
```

```{r Load data, message=FALSE}

# Load National Financial Well-Being Survey data
nfwbs_puf = read_csv("datasets/NFWBS_PUF_2016_data.csv")

# Load Consumer Complaints Data
complaints = read_csv("datasets/Consumer_Complaints.csv")

# Rectify column names
colnames(complaints) = gsub(" ", "_",colnames(complaints))
colnames(complaints) = gsub("-", "_",colnames(complaints))

```

```{r Convert data to long format, message=FALSE}

# Transform Date complaint received by CFPB
complaints$Date_received <- as.Date(complaints$Date_received, "%m/%d/%Y")
complaints$Year_received <- as.numeric(format(complaints$Date_received, "%Y"))
complaints$Month_received <- floor_date(complaints$Date_received, "month")

# Transform Date complaint sent by CFPB to Company
complaints$Date_sent_to_company <- as.Date(complaints$Date_sent_to_company, "%m/%d/%Y")
complaints$Year_sent_to_company <- as.numeric(format(complaints$Date_sent_to_company, "%Y"))
complaints$Month_sent_to_company <- floor_date(complaints$Date_sent_to_company, "month")

# Filter out only Mortgage-related complaints
mort_comp <- filter(complaints, Product == "Mortgage" & grepl("Conventional", Sub_product))

# Re-classify Complaint Types
mort_comp <- mort_comp %>% mutate(
  Issue_type = case_when(
    grepl("Appl", Issue) ~ "Accessibility",
    Issue == "Credit decision / Underwriting" ~ "Accessibility",
    Issue == "Struggling to pay mortgage" ~ "Stressed",
    grepl("collection", Issue) ~ "Stressed",
    grepl("escrow", Issue) ~ "Servicing",
    Issue == "Trouble during payment process" ~ "Servicing",
    TRUE ~ "Other"
    )
  )

# Group by Issue Type & Month
mort_comp_by_issue <- mort_comp %>% 
  group_by(Issue_type, Month_received) %>%
  summarise(num_complaints = n())


# Group by Issue Type & State
mort_comp_by_state <- filter(mort_comp, Year_received == 2017) %>% 
  group_by(Issue_type, State) %>%
  summarise(num_complaints = n())

# Calculate %complaints by State that are Stress related
mort_comp_by_state <- mort_comp_by_state %>%
  group_by(State) %>%
  mutate(comp_perc = num_complaints / sum(num_complaints))
```

```{r Plot}
p1 <- ggplot(mort_comp_by_issue, 
             aes(x=Month_received,
                 y=num_complaints,
                 color=Issue_type,
                 group=Issue_type)) + 
  geom_point() + 
  geom_line()

p1
```

```{r Plot2}
p2 <- ggplot(mort_comp_by_issue, 
             aes(x=Month_received,
                 y=num_complaints,
                 fill=Issue_type,
                 group=Issue_type)) + 
  geom_area() + 
  geom_line(aes(ymax=num_complaints),
            position = "stack")

p2
```

```{r Plot3}
p3 <- ggplot(mort_comp_by_issue, 
             aes(x=Month_received,
                 y=num_complaints,
                 fill=Issue_type)) + 
  geom_bar(stat = "identity")

p3
```

```{r by State}
p4 <- ggplot(mort_comp_by_state, 
             aes(x=State,
                 y=num_complaints,
                 fill=Issue_type)) + 
  geom_bar(stat = "identity")

p4
```

```{r State maps}
states <- map_data("state")

# Convert state names to full names in lowercase 
mort_comp_by_state$Statename <- tolower(abbr2state(mort_comp_by_state$State))

glimpse(mort_comp_by_state)

# Merge with Map Data
comp_state_map <- merge(states, 
                        filter(mort_comp_by_state, Issue_type == "Stressed"), 
                        sort = FALSE, 
                        by.x = "region", 
                        by.y = "Statename")

p5<- ggplot(comp_state_map, aes(long, lat)) + 
  geom_polygon(aes(fill = num_complaints, group=group), color="white") + 
  coord_fixed(1.3)

p5 + labs(colour = "Self-reported Financial Stress", 
          x = "",
          y = "",
          title = "Self-reporting of Financial Stress varies widely across states",
          subtitle = "states vary widely from each other, though no regional trends seen",
          caption = "(based on HMDA Mortgage Performance data by CFPB)",
          tag = "F") + 
  scale_fill_gradientn(colours = terrain.colors(10))
```

```{r Map Stress}
p6<- ggplot(comp_state_map, aes(long, lat)) + 
  geom_polygon(aes(fill = comp_perc, group=group), color="white") + 
  coord_fixed(1.3)

p6
```

```{r Credit Cards}
# Filter out only Mortgage-related complaints
cc_comp <- filter(complaints, Product == "Credit card or prepaid card" & 
                    Sub_product == "General-purpose credit card or charge card")

# Re-classify Complaint Types
cc_comp <- cc_comp %>% mutate(
  Issue_type = case_when(
    Issue == "Struggling to pay your bill" ~ "Stressed",
    TRUE ~ "Other"
    )
  )

# Group by Issue Type & State
cc_comp_by_state <- filter(cc_comp, Year_received == 2017) %>% 
  group_by(Issue_type, State) %>%
  summarise(num_complaints = n())

# Calculate %complaints by State that are Stress related
cc_comp_by_state <- cc_comp_by_state %>%
  group_by(State) %>%
  mutate(comp_perc = num_complaints / sum(num_complaints))

states <- map_data("state")

# Convert state names to full names in lowercase 
cc_comp_by_state$Statename <- tolower(abbr2state(cc_comp_by_state$State))

# Merge with Map Data
cc_state_map <- merge(states, 
                      filter(cc_comp_by_state, Issue_type == "Stressed"), 
                      all.x = TRUE,
                      sort = FALSE, 
                      by.x = "region", 
                      by.y = "Statename")

p7<- ggplot(cc_state_map, aes(long, lat)) + 
  geom_polygon(aes(fill = comp_perc, group=group), color="white") + 
  coord_fixed(1.3)

p7
```

```{r Self-reported Stress by Product}
# Filter out only Mortgage-related complaints
all_comp <- filter(complaints, 
                   Product %in% c("Credit card or prepaid card", 
                                  "Mortgage", 
                                  "Payday loan, title loan, or personal loan",
                                  "Student loan",
                                  "Vehicle loan or lease"))
# Re-classify Complaint Types
all_comp <- all_comp %>% mutate(
  Issue_type = case_when(
    grepl("Struggling to", Issue) ~ "Stressed",
    TRUE ~ "Other"
    )
  )

# Group by Product, Issue Type & State
all_comp_by_state <- filter(all_comp, Year_received == 2017) %>% 
  group_by(Product, Issue_type, State) %>%
  summarise(num_complaints = n())

# Calculate %complaints by State that are Stress related
all_comp_by_state <- all_comp_by_state %>%
  group_by(Product, State) %>%
  mutate(comp_perc = num_complaints / sum(num_complaints))

states <- map_data("state")

# Convert state names to full names in lowercase 
all_comp_by_state$Statename <- tolower(abbr2state(all_comp_by_state$State))

# Merge with Map Data
all_state_map <- merge(states, 
                       filter(all_comp_by_state, Issue_type == "Stressed"), 
                       all.x = TRUE, 
                       sort = FALSE, 
                       by.x = "region", 
                       by.y = "Statename")

p8<- ggplot(all_state_map, aes(long, lat)) + 
  geom_polygon(aes(fill = comp_perc, group=group), color="white") + 
  coord_fixed(1.3)

p8
```

```{r Check}
```