---
title: "Exploratory_Data_Viz"
author: "Darshan Sumant"
date: "January 27, 2019"
output: html_document
---

```{r setup, include=FALSE}

# Load required packages
library("readr")
library("haven")
library("plyr")
library("dplyr")
library("tidyr")
library("stringr")
library("ggplot2")
library("zoo")
library("lubridate")
library("directlabels")
library("wesanderson")

knitr::opts_chunk$set(echo = TRUE)
```

```{r Load data}

# Load Mortgage Performance data

## Delinquency (30-89 days overdue) Rates by month at County, State, State-Area type level 
del_county = read_csv("datasets/CountyMortgagesPercent-30-89DaysLate-thru-2018-06.csv")
del_state = read_csv("datasets/StateMortgagesPercent-30-89DaysLate-thru-2018-06.csv")
del_metro = read_csv("datasets/MetroAreaMortgagesPercent-30-89DaysLate-thru-2018-06.csv")

## Non-Performing Asset (90+ days overdue) Rates by month at County, State, State-Area type level
npa_county = read_csv("datasets/CountyMortgagesPercent-90-plusDaysLate-thru-2018-06.csv")
npa_state = read_csv("datasets/StateMortgagesPercent-90-plusDaysLate-thru-2018-06.csv")
npa_metro = read_csv("datasets/MetroAreaMortgagesPercent-90-plusDaysLate-thru-2018-06.csv")

```

```{r Convert data to long format}

# Delinquency Rates
## Delinquency Rates by County
del_county_long <- gather(select(del_county, -c(RegionType, State, FIPSCode)),
                          key = Month,
                          value = delinquency_rate,
                          convert = TRUE,
                          -Name) %>% 
  mutate(Month = as.Date(paste(Month,"-01",sep="")),
         Mth = format(Month, "%b"))

## Delinquency Rates by State
del_state_long <- gather(select(del_state, -c(RegionType, FIPSCode)),
                         key = Month,
                         value = delinquency_rate,
                         convert = TRUE,
                         -Name) %>% 
  mutate(Month = as.Date(paste(Month,"-01",sep="")),
         Mth = format(Month, "%b"))

## Delinquency Rates by State & Area Type
del_metro_long <- gather(select(del_metro, -c(Name, CBSACode)),
                         key = Month,
                         value = delinquency_rate,
                         convert = TRUE,
                         -RegionType) %>% 
  mutate(Month = as.Date(paste(Month,"-01",sep="")),
         Mth = format(Month, "%b"))


# NPA Rates
## NPA Rates by County
npa_county_long <- gather(select(npa_county, -c(RegionType, State, FIPSCode)),
                          key = Month,
                          value = default_rate,
                          convert = TRUE,
                          -Name) %>% 
  mutate(Month = as.Date(paste(Month,"-01",sep="")),
         Mth = format(Month, "%b"))

## NPA Rates by State
npa_state_long <- gather(select(npa_state, -c(RegionType, FIPSCode)),
                         key = Month,
                         value = default_rate,
                         convert = TRUE,
                         -Name) %>% 
  mutate(Month = as.Date(paste(Month,"-01",sep="")),
         Mth = format(Month, "%b"))

## NPA Rates by State & Area Type
npa_metro_long <- gather(select(npa_metro, -c(Name, CBSACode)),
                         key = Month,
                         value = default_rate,
                         convert = TRUE,
                         -RegionType) %>% 
  mutate(Month = as.Date(paste(Month,"-01",sep="")),
         Mth = format(Month, "%b"))

```
