---
title: "Mapping with sf"
author: "Darshan Sumant"
date: "February 10, 2019"
output: 
  html_document:
    toc: TRUE
    toc_float: TRUE
    code_folding: hide
---

```{r setup, include=FALSE}

# Load required packages
library("rmarkdown")
library("readr")
library("haven")
library("plyr")
library("dplyr")
library("tidyr")
library("stringr")
library("ggplot2")
library("zoo")
library("lubridate")
library("directlabels")
library("wesanderson")
library("ggmap")
library("maps")
library("mapdata")
library("openintro")
library("grid")
library("tools")
library("maptools")
library("lwgeom")

# library(c("cowplot", "googleway", "ggrepel", "ggspatial", "libwgeom", "sf", "rnaturalearth", "rnaturalearthdata"))
library("rgeos")
library("cowplot")
library("googleway")
library("ggrepel")
library("ggspatial")
library("sf")
library("rnaturalearth")
library("rnaturalearthdata")

library("cartogram")
library("recmap")

register_google(key = "AIzaSyCvTsf9fTcIeH9d7WkTVxvYQzu80Hs-EvQ")

knitr::opts_chunk$set(echo = TRUE, warning = FALSE)
```

```{r test_cartogram}
usa <- data.frame(x = state.center$x, 
                  y = state.center$y, 
                  # make the rectangles overlap by correcting lines of longitude distance
                  dx = sqrt(state.area) / 2 / (0.8 * 60 * cos(state.center$y*pi/180)), 
                  dy = sqrt(state.area) / 2 / (0.8 * 60) , 
                  z = sqrt(state.area), 
                  name = state.name)

plot.recmap(usa)

op <- par(mfrow = c(1 ,1), mar = c(0, 0, 0, 0), bg = NA)
plot.recmap(M <- usa[!usa$name %in% c("Hawaii", "Alaska"), ], 
            col.text = 'black', lwd=2)

Cartogram <- recmap(Map <- usa[!usa$name %in% c("Hawaii", "Alaska"), ])
head(Cartogram)

smp <- c(29, 22, 30, 3, 17, 8, 9, 41, 18, 15, 38, 35, 21, 23, 19, 6, 31, 32, 20, 
         28, 48, 4, 13, 14, 42, 37, 5, 16, 36 , 43, 25, 33, 12, 7, 39, 44, 2, 47,
         45, 46, 24, 10, 1,11 ,40 ,26 ,27 ,34)

plot(Cartogram.Area <- recmap(M[smp, ]), 
     col.text = 'black', lwd = 2)

head(M)
plot.recmap(M)
```

```{r test}
dc_loc <- geocode("Washington, D.C.")
dc_map <- qmap(c(lon=dc_loc$lon, lat=dc_loc$lat), source="google", zoom=12)
dc_map

ph_loc <- geocode("Philadelphia")
ph_map <- qmap(c(lon=ph_loc$lon, lat=ph_loc$lat), source="google", zoom=12)
ph_map

ny_loc <- geocode("New York")
ny_map <- qmap(c(lon=ny_loc$lon, lat=ny_loc$lat), source="google", zoom=12)
ny_map

lv_loc <- geocode("Clark County, N.V.")
lv_map <- qmap(c(lon=lv_loc$lon, lat=lv_loc$lat), source="google", zoom=12)
lv_map
```

```{r test2}
world <- ne_countries(scale = "medium", returnclass = "sf")
class(world)

ggplot(data = world) +
    geom_sf(color = "black", fill = "lightgreen") +
    xlab("Longitude") + ylab("Latitude") +
    ggtitle("World map", subtitle = paste0("(", length(unique(world$NAME)), " countries)"))

ggplot(data = world) +
    geom_sf(aes(fill = pop_est)) +
    scale_fill_viridis_c(option = "plasma", trans = "sqrt")

```

```{r test3}
world_points<- st_centroid(world)
world_points <- cbind(world, st_coordinates(st_centroid(world$geometry)))

sites <- data.frame(longitude = c(-80.144005, -80.109), latitude = c(26.479005, 26.83))
sites <- st_as_sf(sites, coords = c("longitude", "latitude"), crs = 4326, agr = "constant")

ggplot(data = world) +
  geom_sf(fill= "antiquewhite") +
  geom_sf(data = sites, size = 4, shape = 23, fill = "darkred") +
  geom_text(data= world_points,aes(x=X, y=Y, label=name),
              color = "darkblue", fontface = "bold", check_overlap = FALSE) +
  annotate(geom = "text", x = -90, y = 26, label = "Gulf of Mexico",
           fontface = "italic", color = "grey22", size = 6) +
  annotation_scale(location = "bl", width_hint = 0.5) +
  annotation_north_arrow(location = "bl", which_north = "true",
                         pad_x = unit(0.75, "in"), pad_y = unit(0.5, "in"),
                         style = north_arrow_fancy_orienteering) +
  coord_sf(xlim = c(-102.15, -74.12), ylim = c(7.65, 33.97), expand = FALSE) +
  xlab("Longitude") +
  ylab("Latitude") +
  ggtitle("Map of the Gulf of Mexico and the Caribbean Sea") +
  theme(panel.grid.major = element_line(color = gray(.5), linetype = "dashed", size = 0.5),
        panel.background = element_rect(fill = "aliceblue"))

```

```{r test4}
states <- st_as_sf(map("state", plot = FALSE, fill = TRUE))
states <- cbind(states, st_coordinates(st_centroid(states)))
states$ID <- toTitleCase(states$ID)
head(states)

states$nudge_y <- -1
states$nudge_y[states$ID == "Florida"] <- 0.5
states$nudge_y[states$ID == "South Carolina"] <- -1.5

counties <- st_as_sf(map("county", plot = FALSE, fill = TRUE))
counties$area <- as.numeric(st_area(counties))


ggplot(data = world) +
    geom_sf() +
    geom_sf(data = states, fill = NA, color= gray(1.0)) +
    geom_sf(data = counties, fill = NA, color = gray(.5)) +
    geom_label(data = states, aes(X, Y, label = ID), size = 5, fontface = "bold",
               nudge_y = states$nudge_y) +
    coord_sf(xlim = c(-88, -78), ylim = c(24.5, 33), expand = FALSE)

```

```{r test5}

phl_dist <- read_sf("datasets/Philly_Council_Districts_2016/Council_Districts_2016.shp")
phl_dist <- cbind(phl_dist, st_coordinates(st_centroid(phl_dist)))
summary(phl_dist)


ggplot(data = phl_dist) + 
  geom_sf() + 
  geom_label(data = phl_dist, aes(X, Y, label = OBJECTID), size = 5, fontface = "bold")

ph_map <- get_map(location = "Philadelphia County, Pennsylvania", zoom = 12)

phl_dist$nudge_y <- 0
phl_dist$nudge_y[phl_dist$OBJECTID == 9] <- -1.0
phl_dist$nudge_y[phl_dist$OBJECTID == 10] <- -0.5

phl_dist$nudge_x <- 0
phl_dist$nudge_x[phl_dist$OBJECTID == 4] <- 0.5
phl_dist$nudge_x[phl_dist$OBJECTID == 2] <- 0.5

ggmap(ph_map) +
  geom_sf(data = phl_dist, inherit.aes = FALSE, 
          fill=NA, color=gray(0.5)) +
  coord_sf(datum = NA) + 
  geom_label(data = phl_dist, inherit.aes = FALSE, 
             aes(X, Y, label = OBJECTID), size = 5, fontface = "bold",
             nudge_y = phl_dist$nudge_y,
             nudge_x = phl_dist$nudge_x)

```